### ISSUE TITLE
Switch between domains - Reseller

### ISSUE THREAD

**Issue by coccoinomane** [GAM-team/GAM#1402]
**Is your feature request related to a problem? Please describe.**
I manage 20+ Google Workspace domains for my clients. All commands that require specifying the domain (say `gam user john@example.com show sendas`) work fine, but if I want to execute a command that does not explicitly contain the domain (say `gam print aliases`), it defaults to my reseller account.

**Describe the solution you'd like**
As a reseller, I would love to have a way to switch between domains, either at the command level (for example, `gam print aliases --domain=example.com`) or at the environment level (for example: `gam switch_to example.com && gam print aliases`).

**Describe alternatives you've considered**
I have looked up GAMADV-XTD3 and the gamselect.sh script, but I would rather use vanilla GAM, if possible.

**Comment by davidsev7** [comment]
I too would love this ability as our school has several domains for "reasons".

**Comment by jondthompson** [comment]
Agreed.

**Comment by tdvaughan** [comment]
I'd love this too - other suggestions such as using multiple oauth files (e.g. https://github.com/GAM-team/GAM/issues/69) haven't worked - e.g. if I try to create a new oauth for another domain, I get "Access blocked: GAM can only be used within its organisation". Unless maybe I'm doing something wrong?

**Comment by taers232c** [comment]
Advanced Gam handle this quite simply:
See: https://github.com/taers232c/GAMADV-XTD3/wiki/gam.cfg#multiple-customers-and-domains <https://github.com/taers232c/GAMADV-XTD3/wiki/gam.cfg#multiple-customers-and-domains>

Ross
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
GAM7 is a merge of GAMADV and standard GAM and solves this. Upgrade and enjoy. Closing this issue now.
