### ISSUE TITLE
Request ability to easily empty a shared drive before deletion

### ISSUE THREAD

**Issue by cliimatta** [GAM-team/GAM#1460]
Google Workspaces administration console does not support deleting shared drives unless it's empty, this is a huge pain if you have a shared drive with tens to hundreds of thousands of files/folders to delete.

I know I can use a combination of GAM commands to list out all files and then delete those files, but it would be nice if that could be condensed into one command line switch like "gam user <email> delete teamdrive <id> --empty-first"

**Comment by jay0lee** [comment]
```gam user admin@domain.com delete shareddrive <id> allowitemdeletion```

should solve this now.
