### ISSUE TITLE
gam print crostelemetry produces unexpected output

### ISSUE THREAD

**Issue by dunlopa** [GAM-team/GAM#1469]
I am using GAM 6.13 on Windows

When running the command "gam print crostelemetry" I get unexpected output.  Here are two examples.  The first example produces expected output which only includes the device ID and the percent of free and used disk space.  The second example produces output that is missing this data and instead includes other storage information.  

**Command:**
`gam print crostelemetry cros_sn NXGM8AA0017451F0007600 fields storageInfo storagepercentonly`
**_Device:_**
Acer Chromebook 11 N7  Chrome OS version 97.0.4692.77
**Output (good):**
deviceId,storageInfo.percentDiskFree,storageInfo.percentDiskUsed
c535a2c0-e11b-457c-a5fd-e556e120e01e,84,16

**Command:**
`gam print crostelemetry cros_sn MP1Y7VZ3 fields storageInfo storagepercentonly`
**Device:**
Lenovo 100e Gen 2 AST  Chrome OS version 94.0.4606.124
**Output (bad - unexpected):**
deviceId,storageInfo.volume.0.volumeId,storageInfo.volume.0.storageFreeBytes,storageInfo.volume.0.storageTotalBytes,storageInfo.volume.1.volumeId,storageInfo.volume.1.storageFreeBytes,storageInfo.volume.1.storageTotalBytes,storageInfo.volume.2.volumeId,storageInfo.volume.2.storageFreeBytes,storageInfo.volume.2.storageTotalBytes,storageInfo.totalDiskBytes
39a1c3cc-c858-428c-aeb8-ac5642f24f74,/media/archive,2039328768,2039328768,/usr/share/oem,11681792,12042240,/media/removable,2039328768,2039328768,22024806400

**Comment by jay0lee** [comment]
closing this as it should be fixed in GAM7 but if the issue persists please re-open.
