### ISSUE TITLE
macOS 12.1 (21C52) ERROR: assets value not found

### ISSUE THREAD

**Issue by dan-snelson** [GAM-team/GAM#1470]
On macOS 12.1 (21C52), the [Mac instructions](https://github.com/GAM-team/GAM/wiki#mac-and-linux-users) are not currently working.

Full steps to reproduce the issue:
1. Launch Terminal
2. Enter: `bash <(curl -s -S -L https://git.io/install-gam)`
3. Observe the output:
```
You are running MacOS 12.1
Checking GitHub URL https://api.github.com/repos/jay0lee/GAM/releases for latest GAM release (unauthenticated)...

Getting file and download URL...

ERROR: assets value not found in JSON value of:

{'message': 'Moved Permanently', 'url': 'https://api.github.com/repositories/20185174/releases', 'documentation_url': 'https://docs.github.com/v3/#http-redirects'}
```

**Comment by jay0lee** [comment]
This was due to:

https://groups.google.com/g/google-apps-manager/c/g4x5ZQx-CBI

I've fixed it in the install script now though it may take an hour or so for your machine to pickup the updated script.

**Comment by dan-snelson** [comment]
Confirmed working; thanks Obi-@jay0lee!
