### ISSUE TITLE
Executing GAM commands resulted in Error

### ISSUE THREAD

**Issue by dominicplanview** [GAM-team/GAM#1475]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
`using this command: gam csv woodbine.csv gam user "~primaryEmail" signature file Email_Signature_Original.txt replace First "~name.givenName" replace Last "~name.familyName" replace Title "~organizations.0.title" replace WPType "~phones.1.type" replace WPhone "~phones.1.value" replace PType "~phones.0.type" replace Phone "~phones.0.value" replace Email "~primaryEmail" replace Suite "~suite" replace Address "~addresses.0.formatted" replace CityProv "~city" replace PostalCode "~PostalCode"`

Expected Outcome:

Once the command executes, it'll pull from the csv file with contents in the cell and create/update our users' email signature

Actual outcome (what errors or bad behavior do you see instead?):

> Traceback (most recent call last):
>   File "gam\__main__.py", line 49, in <module>
>   File "gam\__main__.py", line 44, in main
>   File "gam\__init__.py", line 11385, in ProcessGAMCommand
>   File "csv.py", line 97, in fieldnames
>   File "codecs.py", line 322, in decode
>   File "encodings\utf_8_sig.py", line 69, in _buffer_decode
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 691: invalid start byte
> [27216] Failed to execute script '__main__' due to unhandled exception!

**Comment by taers232c** [comment]
Assuming that you're on a PC, make a slight change:
gam csv woodbine.csv charset latin1 .....

Ross

**Comment by dominicplanview** [comment]
@taers232c Thank you for the response. All is working now! Cheers! :)
