### ISSUE TITLE
Linux version installation issues 2.28 x86_64 not failing over to legacy. 

### ISSUE THREAD

**Issue by charlielove** [GAM-team/GAM#1477]
**Is your feature request related to a problem? Please describe.**
Install/upgrade is trying to download 2.27 version giving error on linux-x86_64-glibc2.28.

ERROR: Attribute: browser_download_url for linux-x86_64-glibc2.27.tar.xz version 6.14 not found

on installation or upgrade.

**Describe the solution you'd like**
Download/installation option which is Google Cloud Shell compatible. 

**Describe alternatives you've considered**
Have upgraded to 6.13 which is most recent version that works.

**Comment by charlielove** [comment]
Solved - I think it's a bug with the install-script.  Line 31 has 2.27 listed but there is no 2.27 release for 6.14 or 6.15 for download.

Also, if the install-gam file is edited for 2.28 there is no gam-6.15-linux-x86_64-glibc2.28 release only 2.31.

Solve by editing install-gam bash to force legacy on Cloud Shell.

**Comment by jay0lee** [comment]
I just tested and this should be solved now. Note that the glibc 2.28
builds are for arm and aarch64, not x86_64. For x86_64 there's a glibc 2.31
build and then everything else (including Cloud Shell) will use legacy.

Jay Lee
