### ISSUE TITLE
gam print deleted users uid

### ISSUE THREAD

**Issue by marcelvv83** [GAM-team/GAM#1480]
I've got a mass deletion because of Google Sync failure. Afterwards the Sync created new users, with the same email/firstname/lastname.
To Undelete I need a UID.

If "gam print users deleted_only" could be extended with UID, to print the UID of the users.

Currently I'm trying to parse the output, which I piped to a txt file. But that's not working..

**Comment by jay0lee** [comment]
Please use the existing groups discussion for this.
