### ISSUE TITLE
Terms of Service Issues

### ISSUE THREAD

**Issue by cbitterfield-pdl** [GAM-team/GAM#1484]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Initial Installation will produce the issues.
2.
3.

Expected outcome (what are you trying to do?):

Initial Installation

Actual outcome (what errors or bad behavior do you see instead?):

ERROR: 400: The terms of service 'chrome-policy' for service(s) 'chromepolicy.googleapis.com' must be accepted. Please visit the Developers Console to accept the terms of service (https://console.developers.google.com/terms/chrome-policy).
Help Token: Ae-hA1OcH4krwr8tkexV_2fvML-eY_aFpsoxBf87Aqv5RxhqpQBDLGI4War-880sFRxrYnT1DATZEzXsm3JaquT5bFntKDFzLKheIWnd5Wxd2cfD - 400
Project creation failed. Trying again. Say N to skip project creation.

Recommended Fix:

On your installation have a list of the URLs for accepting all of the terms of service required. I had to restart the installation 5 or 6 times to accept terms of services. 

i.e. 

Developers Console to accept the terms of service (https://console.developers.google.com/terms/classroom)
https://console.developers.google.com/terms/appsadmin
https://console.developers.google.com/terms/universal
https://console.developers.google.com/terms/calendar
https://console.developers.google.com/terms/chrome-policy
https://console.developers.google.com/terms/cloud

**Comment by jay0lee** [comment]
This was fixed in 6.17
