### ISSUE TITLE
condition for granting _GROUPS_EDITOR_ROLE not working...

### ISSUE THREAD

**Issue by henningkessler** [GAM-team/GAM#1494]
Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
Yes, I am using version 6.17 on macOS 10.15.7
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
Yes, I am using this command:
```
√ admin@station[~]% gam create admin someone@acme.com _GROUPS_EDITOR_ROLE customer condition nonsecuritygroup
```
to give a user the groups editor role for the whole domain but limit  it to non-security groups

Result is:
```
Giving someone@acme.com admin role _GROUPS_EDITOR_ROLE for CUSTOMER

ERROR: 403: The operation is not supported - forbidden
```

I can run the command successfully for the same user without the condition...

**Comment by jay0lee** [comment]
closing as this issue should be fixed in latest GAM7 release.
