### ISSUE TITLE
Getting ERROR: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

### ISSUE THREAD

**Issue by jeffrymj** [GAM-team/GAM#1518]
Getting this error when using GAM on our prod network that has MitM policies.  Tried implementing the GAM_CA_FILE for our PEM file, but not working.  Are there other URLs we need to allow besides accounts.google.com and *.googleapis.com?

* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam info domain 

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

**Comment by jay0lee** [comment]
Can you start a discussion on the group?

groups.google.com/g/google-apps-manager
