### ISSUE TITLE
Feature request for Gam command to copy/transfer classrooms

### ISSUE THREAD

**Issue by HVS-IT** [GAM-team/GAM#1530]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue. - Yes
* I am typing the command as described in the GAM Wiki at https://github.com/GAM-team/GAM/wiki - Yes

Apologies if this is not the right place, I'm taking the understanding of the "Enhancement" label as a sort of feature request, if I am incorrect please point me to the relevant section.

There is an option in Google Classroom to Copy a class, this creates a new classroom with some of the content from the original.

Is there any way to implement this in gam so it can be scripted? and further from that is there a way to copy the content from one existing classroom to another existing classroom?

The use case for this is when generating new classrooms each year that teachers want to have content from the last year on the new one instead of having to redo them.

**Comment by taers232c** [comment]
Rob,

This is already a feature in Advanced GAM: https://github.com/taers232c/GAMADV-XTD3/wiki/Classroom-Courses#create-and-update-courses

https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM

Ross
--
***@***.***
