### ISSUE TITLE
Group Picture setting

### ISSUE THREAD

**Issue by robertoandrade** [GAM-team/GAM#1532]
**Is your feature request related to a problem? Please describe.**
In the old google groups UI we had the option to define a custom Picture for the group which doesn't exist on the new UI. Is there a way to set that using the API and as such using GAM?
See screenshots for reference: https://www.alaska.edu/google/groups/lessons/Group_Settings_Appearance.html

**Describe the solution you'd like**
A command option to set google group picture

**Describe alternatives you've considered**
Using gravatar or similar but don't think most email clients will respect that, especially Gmail.

**Additional context**

**Comment by jay0lee** [comment]
There's no API for assigning group pictures. There's no way for GAM to do this.
