### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by mherbig1971** [GAM-team/GAM#1543]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.Go to the following link in your browser:
2.https://gam-shortn.appspot.com/nrtktb
3.Error 400: invalid_request

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):
![image](https://user-images.githubusercontent.com/109601424/179760591-c6af1c97-ffc2-4203-975d-d50ef295d324.png)

**Comment by jay0lee** [comment]
You are not running the most recent version of GAM.

Upgrade.
