### ISSUE TITLE
wrong path to run GAM

### ISSUE THREAD

**Issue by ScaryHouse** [GAM-team/GAM#1548]
>>If you need help with GAM, please do not file an issue here, it will be closed and ignored.
Please post your question to the GAM discussion group where other admins are ready and willing to help:
https://groups.google.com/g/google-apps-manager

It looks like all Google Groups regarding GAM are closed. I hope someone will help me here.

I am a newbie and have had trouble installing GAM locally and setting up project and scopes. 
I believe I have finally installed basic version of GAM, but I think an earlier attempted install of advanced version is contradicting my commands. For example I attempt to simply run:

`gam info domain`

but I get result of:

`zsh: no such file or directory: /Users/computerservices/bin/gamadv-xtd3/gam`

my install path is actually:

/Users/computerservices/bin/gam/gam

How do I get commands to access /bin/gam/gam ?

**Comment by taers232c** [comment]
This error indicates that you've installed Advanced GAM.
Send me a Meet/Zoom invitation are ross.scroggs @ gmail.com and I'll help sort this out.

Ross

**Comment by ScaryHouse** [comment]
I guess I'd turned Google Groups off for myself. (Or never turned it on!)
Thanks for the heads up. I'll re-post in the Google forum.
