### ISSUE TITLE
GAM just stopped working

### ISSUE THREAD

**Issue by amirjawaidpk** [GAM-team/GAM#1557]
Hi,

I am using Mac OS Monterey on an M1 Pro laptop. (IOS 12.5.1). My GAM has just suddenly stopped working, i am on the latest 6.25 version. Any command i enter, i get the error "ERROR: [Errno 2] No such file or directory"

**Comment by jay0lee** [comment]
6.25 and newer include a file called roots.pem in the .zip file that you MUST have in the GAM folder. Previously this file was folded into the GAM binary but now it's separate to make it more clear what GAM is doing here. See:

https://github.com/GAM-team/GAM/issues/1555

for more background.

**Comment by amirjawaidpk** [comment]
> 6.25 and newer include a file called roots.pem in the .zip file that you MUST have in the GAM folder. Previously this file was folded into the GAM binary but now it's separate to make it more clear what GAM is doing here. See:
> 
> #1555
> 
> for more background.

ah!! thanks, silly me i seemed to have missed this part .....thx again!!
