### ISSUE TITLE
WinError 10060 - Timeout

### ISSUE THREAD

**Issue by SergioCortese** [GAM-team/GAM#1559]
Hello,

there are no real steps to reproduce the error. I'm just getting it about 80% of the time on every single command. As I would like to execute a sequence of correlated commands in a batch, this is getting very tiring because I cannot and I have to insert the commands one by one, many times until they have success.

I understand that this may not be a direct GAM problem, meaning that for some reason it may depend on the answer from the server being very slow. 
What I'm asking is if there is a way to raise the timeout from the GAM side so that commands can complete.

Hope to have been clear enough. 

Thanks

**Comment by jay0lee** [comment]
The timeout is already very high, I don't think raising it higher will help here.

What you might want to look at is running GAM itself on a GCP VM or Google Cloud Shell so that it's connectivity is no longer an issue.
