### ISSUE TITLE
Remove a User from All Groups not working

### ISSUE THREAD

**Issue by Heaven-Crow** [GAM-team/GAM#1563]
Tired removing email groups from email address by using "gam user user@domain.com delete groups" command.
I got the message: "user@domain.com is in 0 groups." and the email address is still in the email group.

The command works last week.

I've tried reinstalling and downgrade to v6.24, doesn't work.

Thanks

**Comment by taers232c** [comment]
Over the last couple of weeks, I've seen a delay between changing group membership with GAM/Google Directory API and when the change is reflected at Google.

Ross
----
Ross Scroggs
***@***.***
