### ISSUE TITLE
Error installing HTTPSConnection... Full Error in Post

### ISSUE THREAD

**Issue by rgilman76** [GAM-team/GAM#1565]
Installing GAM on New server
Never Had Gam Before on this machine
Machine is not using a proxy. 

Error is generated after pasting the "Unable to Connect" link from another computer back to the server. 

Error message is below

**ERROR: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DAA6A7AF80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))**

Let me know what additional information you need.

**Comment by taers232c** [comment]
I'd start by installing the current version 6.25
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
And then running:

gam checkconn

But the answer is that some software or device on your network is
interfering with GAM's connections.

Jay

**Comment by rgilman76** [comment]
So I solved this myself. 

The problem is that command prompts in windows aren't, by default, proxy aware, 

The resolution was to set the system variables for HTTP_PROXY, HTTPS_PROXY, FTP_PROXY. 

This allows the Command prompt in windwos to utalize the PRoxy server.

**Comment by jay0lee** [comment]
Proxy is covered in the Wiki. You shouldn't need FTP_PROXY

https://github.com/GAM-team/GAM/wiki#using-gam-with-a-http-proxy
