### ISSUE TITLE
GAM calendar ACL will not work on sub-domain

### ISSUE THREAD

**Issue by ferhotguy** [GAM-team/GAM#1573]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:

gam calendar [xyz...@group.calendar.google.com](https://groups.google.com/) add owner [targe...@domain.com](https://groups.google.com/) sendnotifications false
Calendar: [xyz...@group.calendar.google.com](https://groups.google.com/), Add ACL: (Scope: [user:targe...@domain.com](https://groups.google.com/), Role: owner)

ERROR: 404: Not Found - notFound

gam calendar [xyz...@group.calendar.google.com](https://groups.google.com/) add acls owner [targe...@domain.com](https://groups.google.com/) sendnotifications false

ERROR: Role must be one of editor, freebusy, freebusyreader, owner, read, reader, writer, none; got acls

Expected outcome (what are you trying to do?):
Trying to grant access to a shared calendar, it works fine the ones without sub-domain of google workspace

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: 404: Not Found - notFound

**Comment by ferhotguy** [comment]
GAM 6.30 - https://jaylee.us/gam - pyinstaller
Jay Lee <jay0lee@gmail.com>
Python 3.11.0 64-bit final
google-api-python-client 2.65.0
MacOS Monterey 12.6.1 x86_64

All APIs are authorized & Super-Admin at the workspace

**Comment by jay0lee** [comment]
closing this as it's old. If you're still having issues please first reach out on the discussion group before opening a bug. https://git.io/gam-group.
