### ISSUE TITLE
[127556] Failed to execute script '__main__' due to unhandled exception!

### ISSUE THREAD

**Issue by TS-02** [GAM-team/GAM#1588]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki - Yes

**Full steps to reproduce the issue:**
1. Opened command prompt.
2. Entered the following GAM command - 'gam create guardianinvite <guardian email> <student email>'
3. Received the following error message -

**Expected outcome (what are you trying to do?):**
Send Google Classroom invite to guardians email address.

**Actual outcome (what errors or bad behavior do you see instead?):**

Traceback (most recent call last):
  File "gam\__main__.py", line 50, in <module>
  File "gam\__main__.py", line 45, in main
  File "gam\__init__.py", line 11356, in ProcessGAMCommand
  File "gam\__init__.py", line 2153, in doInviteGuardian
  File "gam\__init__.py", line 997, in buildGAPIObject
  File "gam\__init__.py", line 925, in getValidOauth2TxtCredentials
  File "gam\auth\oauth.py", line 467, in refresh
  File "gam\auth\oauth.py", line 475, in _locked_refresh
  File "google\oauth2\credentials.py", line 228, in refresh
  File "google\oauth2\reauth.py", line 338, in refresh_grant
  File "google\oauth2\_client.py", line 60, in _handle_error_response
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
[127556] Failed to execute script '__main__' due to unhandled exception!

**Comment by taers232c** [comment]
Try:
gam oauth delete
gam oauth create

Ross

----
Ross Scroggs
***@***.***

**Comment by TS-02** [comment]
Hi @taers232c,

Thank you for your reply.

I didn't ordinally set up GAM, but could you confirm what the above commands do.

If I do run both commands, would I need to set everything up again as mentioned below?

![GAM Authorisation](https://user-images.githubusercontent.com/52854743/208629639-316324f0-6793-4886-90c2-ef55d747b211.png)

Kind Regards,

Tamoor

**Comment by TS-02** [comment]
Hi Ross,

Thank you for confirming that for me.

By doing this, would I need to do anything else?

And, just to confirm, how often would the credentials expire? Is this a monthly/yearly thing?

Kind Regards,

Tamoor

**Comment by taers232c** [comment]
Tamoor,

That should be enough.

It's not a monthly/yearly thing, changing the super admin password forces them to expire.

Ross
----
Ross Scroggs
***@***.***

**Comment by TS-02** [comment]
Hi Ross,

Thanks for confirming. Our admin password for Google Workspace hasn't changed recently so I'm not sure what caused this to occur.

I will try those two commands and provide an update shortly.

Kind Regards,

Tamoor

**Comment by TS-02** [comment]
Hi @taers232c,

I entered the commands that you provided and continued to the authorization step.

When I went to the verification link I received the following error message on the web page.

![image](https://user-images.githubusercontent.com/52854743/210353827-9203b11b-1e4f-43f7-8ffa-4b76f536e98f.png)

Am I missing something?

Kind Regards,

Tamoor

**Comment by taers232c** [comment]
Tamoor,

I'm in California (PST), what is your time zone? I'd like to arrange a Meet/Zoom session.

Ross
----
Ross Scroggs
***@***.***

**Comment by TS-02** [comment]
Hi Ross,

I'm based in the UK so there's an 8 hour time gap.

Would you be available anytime between 11AM - 1PM PST?

Kind Regards,

Tamoor

**Comment by taers232c** [comment]
Tamoor,

Yes

Ross
----
Ross Scroggs
***@***.***

**Comment by TS-02** [comment]
Hi Ross,

Thank you for your update. I will need to double check something with my colleague regarding the account used. 

If that's okay with yourself, I will provide an update as soon as possible.

Kind Regards,

Tamoor

**Comment by taers232c** [comment]
OK
----
Ross Scroggs
***@***.***

**Comment by TS-02** [comment]
Hi Ross,

I hope you've been well.

Just a quick update. I found that re-installing GAM itself resolved this issue.

It seemed the current version I was on caused an issue when attempting to re-authenticate with our admin email address.

Thank you for the assistance though.
