### ISSUE TITLE
ERROR - refresh_token - Setting up a new install

### ISSUE THREAD

**Issue by Charlie2026** [GAM-team/GAM#1611]
Full steps to reproduce the issue:
1. Trying to install a fresh copy of GAM on multiple computers, with two different internet connections (to ensure it wasn't a filtering issue), produces the same result.
2. After authorizing GAM via the browser link, I get the message to say "The Authentication flow has completed, then an error message

Expected outcome (what are you trying to do?): Set up a new GAM install.

Actual outcome (what errors or bad behavior do you see instead?):
**"ERROR: ('invalid_request: Missing required parameter: refresh_token', {'error': 'invalid_request', 'error_description': 'Missing required parameter: refresh_token'})"**
then
**"Project creation failed. Trying again, Say n to skip project creation".**

I've looked on github for anyone else having this issue, but I can't find anyone.

Any help would be appreciated.

**Comment by jay0lee** [comment]
If this is still an issue for you please reach out to the discussion group for help:

https://groups.google.com/g/google-apps-manager
