### ISSUE TITLE
Account related forwarding infos in `gam info user`

### ISSUE THREAD

**Issue by mathi-ryte** [GAM-team/GAM#1612]
**Is your feature request related to a problem? Please describe.**
We had an issue where an user account was forwarding emails to a group, but we couldn't figure out why.
We had global forwarding disabled, BUT we forgot that domain internal forwarding was enabled.
We can not see this user related setting in GWS GUI or GAM `gam info user` and have to login to the account itself to check.

**Describe the solution you'd like**
It would be really helpful if `gam info user` can also show if forwarding is active for an account and where it's pointing to.

**Describe alternatives you've considered**
-

**Additional context**
Thank you for your work! It's amazing for us as admins that this exists!

**Comment by taers232c** [comment]
See: https://github.com/GAM-team/GAM/wiki/ExamplesEmailSettings#forwarding
----
Ross Scroggs
***@***.***

**Comment by mathi-ryte** [comment]
Hi Ross, thanks for the quick reply.

Unfortunately this is not what I meant. 

I know you can retrieve this info separately, but this is related to a practical use; If you are trouble shooting and checking on account infos generally there is often no time or no concrete initial thought behind checking the basics.

What I was trying to ask is if it's possible to add some more (in my opinion) fundamentals for GWS admins to the info output.

In this case forwarding infos for an account, as we are otherwise relatively blind if a user has setup that fwding and we do not have the clear head to remember to check that manually with a separate command.

Thanks for considering.
Best
Matthias

**Comment by jay0lee** [comment]
It may be fundamental for your usage of Workspace but it's not for other
customers, some only use Drive, some are only using Cloud Identity with GCP.

I'd suggest writing a simple batch / shell script that runs all the GAM
commands you need for the given user. Something as simple as:

----
set /a user=%1
gam info %user%
gam user %user% show forward
----

Jay

**Comment by devilshezi0** [comment]
> **Is your feature request related to a problem? Please describe.**
> We had an issue where an user account was forwarding emails to a group, but we couldn't figure out why.
> We had global forwarding disabled, BUT we forgot that domain internal forwarding was enabled.
> We can not see this user related setting in GWS GUI or GAM `gam info user` and have to login to the account itself to check.
> 
> **Describe the solution you'd like**
> It would be really helpful if `gam info user` can also show if forwarding is active for an account and where it's pointing to.
> 
> **Describe alternatives you've considered**
> -
> 
> **Additional context**
> Thank you for your work! It's amazing for us as admins that this exists!
