### ISSUE TITLE
Creating GAM Project - Unhandled Exception error (1312) due to UnboundLocalError

### ISSUE THREAD

**Issue by LiamWatson28** [GAM-team/GAM#1615]
I am trying to install GAM on Google Cloud Shell. It would be the latest version (6.51) as I am using the command to download it. At the project creation stage, I get through the verification code part. It then enables the APIs and gets to the "Creating Service Account" part, after which I get this:

Creating Service Account
Traceback (most recent call last):
  File "gam/__main__.py", line 49, in <module>
  File "gam/__main__.py", line 44, in main
  File "gam/__init__.py", line 11645, in ProcessGAMCommand
  File "gam/__init__.py", line 7775, in doCreateProject
  File "gam/__init__.py", line 7412, in _createClientSecretsOauth2service
  File "gam/__init__.py", line 8036, in doCreateOrRotateServiceAccountKeys
UnboundLocalError: cannot access local variable 'validity_hours' where it is not associated with a value
[1312] Failed to execute script '__main__' due to unhandled exception!

Full steps to reproduce the issue:
1. Run `bash <(curl -s -S -L https://gam-shortn.appspot.com/gam-install)` to download GAM.
2. Type "N" when prompted about running a full browser on the machine.
3. Type "Y" to set up Google API project for GAM
4. Follow link to get verification code and paste URL/code into terminal.
5. Wait until creation fails.

**Comment by taers232c** [comment]
PR #1614 fixes this error.

**Comment by johngoolsky** [comment]
@taers232c I'm experiencing this issue as well. My apologies, as I'm just learning my way around GitHub - I see that the commit was merged and that 15/16 checks was passed - does that mean we're still waiting on the issue to be fixed?

**Comment by taers232c** [comment]
Jay has fixed the code it has not been released.

**Comment by johngoolsky** [comment]
@taers232c got it - thank you for the clarification!

**Comment by jay0lee** [comment]
It's building now...

https://github.com/GAM-team/GAM/actions/runs/4439412613

Jay Lee

**Comment by johngoolsky** [comment]
Very cool - thank you @jay0lee!

**Comment by jay0lee** [comment]
6.52 is out now.
