### ISSUE TITLE
Unable to Print Forwarding Addresses

### ISSUE THREAD

**Issue by jhawthorn411** [GAM-team/GAM#1616]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/GAM-team/GAM/wiki

Full steps to reproduce the issue:
1.  Execute gam all users print forwardingaddresses > (file path) in command prompt
2. Wait
3. Eventual error

Expected outcome (what are you trying to do?):
Trying to execute an export of addresses that have forwarding enabled  I'm running it on a Windows 10 environment using GAM 6.50, and just trying to export to a local repository on my computer using  gam all users print forwardingaddresses > (file path).  

Actual outcome (what errors or bad behavior do you see instead?):

After a very long wait, we get the error ERROR: Authentication Token Error - invalid_grant: Invalid JWT: Token must be a short-lived token (60 Minutes) and in a reasonable timeframe.  Check your iat and exp values and use a clock with skew to account for click differences between systems. This outputs a blank csv file in the chosen location.  I have checked some forums on this, and they all suggest my clock is out of sync.  however, it is completely synced up with our domain upon checking. 

To note:  I tried to do a show instead of a print for address forwarding to see if it would work in general, but due to the fact that we have over 58k addresses being pulled, it takes hours to process and doesn't fit all in one command prompt screen.  The farthest It's gotten through a show all is roughly 22k out of the 58k.  It fails out with Error 11001 Getaddrinfo failed and no additional elaboration.

**Comment by devilshezi0** [comment]
> The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.
> 
> Please confirm the following:
> * I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
> * I am typing the command as described in the GAM Wiki at https://github.com/GAM-team/GAM/wiki
> 
> Full steps to reproduce the issue:
> 1.  Execute gam all users print forwardingaddresses > (file path) in command prompt
> 2. Wait
> 3. Eventual error
> 
> Expected outcome (what are you trying to do?):
> Trying to execute an export of addresses that have forwarding enabled  I'm running it on a Windows 10 environment using GAM 6.50, and just trying to export to a local repository on my computer using  gam all users print forwardingaddresses > (file path).  
> 
> Actual outcome (what errors or bad behavior do you see instead?):
> 
> After a very long wait, we get the error ERROR: Authentication Token Error - invalid_grant: Invalid JWT: Token must be a short-lived token (60 Minutes) and in a reasonable timeframe.  Check your iat and exp values and use a clock with skew to account for click differences between systems. This outputs a blank csv file in the chosen location.  I have checked some forums on this, and they all suggest my clock is out of sync.  however, it is completely synced up with our domain upon checking. 
> 
> To note:  I tried to do a show instead of a print for address forwarding to see if it would work in general, but due to the fact that we have over 58k addresses being pulled, it takes hours to process and doesn't fit all in one command prompt screen.  The farthest It's gotten through a show all is roughly 22k out of the 58k.  It fails out with Error 11001 Getaddrinfo failed and no additional elaboration.
>

**Comment by jay0lee** [comment]
closing this as it sounds like a specific configuration issue. If you are still seeing this issue though please start a discussion in git.io/gam-group or git.io/gam-chat.
