### ISSUE TITLE
Does GAM need "admin workspace" ? 

### ISSUE THREAD

**Issue by iautran** [GAM-team/GAM#1619]
Hi,
I didn't find the prerequisites, so sorry if my question seems basic but I have an account with many email (pro and personal email in a professional mailbox).
I would like to export all my personal emails stored in that mailbox but I have seen that the first step is to declare the domain admin workspace email address.

Does it mean that I can't use GAM ? 

THank you

**Comment by jay0lee** [comment]
Please request help in the discussion group, this section is for reporting bugs:

https://groups.google.com/g/google-apps-manager
