### ISSUE TITLE
Allow British Spelling.

### ISSUE THREAD

**Issue by calebcze** [GAM-team/GAM#1620]
Hi there,

I ran into a pain point yesterday when I tried to update users departments. Here was my command.
`gam update user ~Email organisation department "students" primary`

This didn't work though, as I had used the British spelling _organisation_ instead of the necessary _organization_.
Would it be possible to allow the British spelling of such words?

**Comment by taers232c** [comment]
I can do that, send me a ist of keywords.

Ross
----
Ross Scroggs
***@***.***

**Comment by calebcze** [comment]
Hi Ross,

Here are the commands I identified as needing to be changed.
There may be a few more as I was working off a cheat sheet which has no
guarantees of being up to date.
For the time, here is the list.

Current GAM Spelling
Requested Alias
backgroundcolor
backgroundcolour
textcolor textcolour
colorindex colourindex
htmlcolor htmlcolour
foregroundcolor foregroundcolour
color colour
organization organisation
organizations organisations
organizationname
organisationname
fileorganizer fileorganiser
costcenter costcentre
license licence
licenses licences
nolicenses nolicences


Caleb Czepanski
Technical Consultant, Entity Hub Ltd

 0508 ENTITY  <+(09)+0508+ENTITY>   www.entity.nz  <https://www.entity.nz/>
   ***@***.***

 12 Sharkey Street, Manukau City Centre, Auckland 2104
<https://maps.google.com/?q=12%20Sharkey%20Street,%20Manukau%20City%20Centre,%20Auckland%202104>

**Comment by taers232c** [comment]
Thanks, I'll work on it.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
Please note that I'll be doing this in Advanced GAM. I'll get to standard GAM later.

**Comment by calebcze** [comment]
Thanks for that Ross.

Glad to have been able to make any sort of contribution. :)


Caleb Czepanski
Technical Consultant, Entity Hub Ltd

 0508 ENTITY  <+(09)+0508+ENTITY>   www.entity.nz  <https://www.entity.nz/>
   ***@***.***

 12 Sharkey Street, Manukau City Centre, Auckland 2104
<https://maps.google.com/?q=12%20Sharkey%20Street,%20Manukau%20City%20Centre,%20Auckland%202104>

**Comment by taers232c** [comment]
British spellings now available in Advanced GAM 6.54.03
Send me a Meet/Zoom invitation.

**Comment by calebcze** [comment]
Hi Ross,

That's great, thank you very much.
Here's a meet link.
https://meet.google.com/fkk-scgp-ynu

Thanks,
Caleb


Caleb Czepanski
Technical Consultant, Entity Hub Ltd

 0508 ENTITY  <+(09)+0508+ENTITY>   www.entity.nz  <https://www.entity.nz/>
   ***@***.***

 12 Sharkey Street, Manukau City Centre, Auckland 2104
<https://maps.google.com/?q=12%20Sharkey%20Street,%20Manukau%20City%20Centre,%20Auckland%202104>
