### ISSUE TITLE
"gam print mobile" doesn't include endpoint Mac/Window/Linux systems

### ISSUE THREAD

**Issue by jhaar** [GAM-team/GAM#1622]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam version == 6.57
2. gam print mobile
3.

Expected outcome (what are you trying to do?):

When I use the Google web console to lookup "Devices -> Mobile & endpoints" I can see all our company Android, iOS, Windows, Mac and Linux systems (the latter three install Google "endpoint verification" extension in Chrome which feeds their device data into Google Workspaces)

Actual outcome (what errors or bad behavior do you see instead?):

"gam" only shows Android and iOS. 

It's arguable that these "endpoint" devices aren't in scope - but Google seems to be calling "Mobile" now "Mobile and endpoints" - which does imply they should be covered?

**Comment by jay0lee** [comment]
This is working as intended. The mobile API only returns mobile devices and excludes company -owned devices. This is the legacy API and is not recommended:

https://developers.google.com/admin-sdk/directory/reference/rest/v1/mobiledevices/list

The recommendation is to use

gam print devices

Which calls cloud Identity devices API:

https://cloud.google.com/identity/docs/reference/rest/v1/devices/list

**Comment by jhaar** [comment]
ohhhh! Thanks for letting me know :-)
