### ISSUE TITLE
Add/Remove users from Chat Spaces

### ISSUE THREAD

**Issue by ianreger** [GAM-team/GAM#1633]
**Is your feature request related to a problem? Please describe.**

- Whenever I add new users, I am responsible for adding users to a handful of spaces depending on their role. I already have some .bat files to create users from a .csv, and it would be nice to add an extra couple lines to the script to add those users to spaces automatically. 

**Describe the solution you'd like**
- Open gam
- type: gam spaces add SPACEID USER

**Describe alternatives you've considered**

**Additional context**

**Comment by jay0lee** [comment]
I believe this is fully implemented now. Closing but feel free to re-open if the API supports something and GAM doesn't.
