### ISSUE TITLE
Migrating from reports to the audit and investigation tool

### ISSUE THREAD

**Issue by elorrtu5746** [GAM-team/GAM#1635]
Google has recently replaced the audit logs with the log event data of the audit and investigation tool in the Google admin console. This allows for easier query and filtering, additional and clearer (for the most part) data sources, and most importantly - any query is recorded in the Admin event logs, which allows for control over this incredibly powerful tool.

I was wondering if you've considered migrating the use of reports in GAM to the newer audit and investigation tool, which would allow for the mentioned benefits.

**Comment by jay0lee** [comment]
I'm not understanding what you are looking for here. The Google APIs for reporting have NOT changed as far as I know. Only the user interface for searching and interacting with that data in the admin console has changed and that does not impact GAM's usage of the APIs.

Put another way, what are you trying to do via GAM that you can do in the admin console and feel you can't do via GAM today?

Jay

**Comment by elorrtu5746** [comment]
I want all GAM report query commands to be logged in the admin audit log like they are in the admin console.

**Comment by jay0lee** [comment]
GAM has no control over how Google servers audit and report GAM commands / API calls. Changes here would need to happen on the Google end.
