### ISSUE TITLE
 CreatingClientSecretsFile - Service(s) not found or permission denied

### ISSUE THREAD

**Issue by henningkessler** [GAM-team/GAM#1638]
Hello, I am trying to follow the [How To ](https://github.com/GAM-team/GAM/wiki/CreatingClientSecretsFile) but the process is failing with this error
```Not found or permission denied for service(s): appsactivity. ```

Regards

Henning

**Comment by jay0lee** [comment]
Marking this as closed as others have not reported issues using latest GAM7 release. If you are still seeing issues please reach out to https://git.io/gam-group for assistance.
