### ISSUE TITLE
Temporary error: userRateLimitExceeded - User rate limit exceeded., Backing off: 60 seconds, Retry: 7/10

### ISSUE THREAD

**Issue by srknoztrk53** [GAM-team/GAM#1643]
Temporary error: userRateLimitExceeded - User rate limit exceeded., Backing off: 16 seconds, Retry: 4/10
Temporary error: userRateLimitExceeded - User rate limit exceeded., Backing off: 32 seconds, Retry: 5/10
Temporary error: userRateLimitExceeded - User rate limit exceeded., Backing off: 60 seconds, Retry: 6/10
Temporary error: userRateLimitExceeded - User rate limit exceeded., Backing off: 60 seconds, Retry: 7/10

How can we make it log out automatically when we get this error? It keeps returning this error. I know user 750gb limit. but it would be better if he didn't try again.

**Comment by jay0lee** [comment]
please post your question to:

https://groups.google.com/g/google-apps-manager

and include details like the GAM command you are running so we can assist you.

**Comment by srknoztrk53** [comment]
> Lütfen sorunuzu şu adrese gönderin:
> 
> https://groups.google.com/g/google-apps-manager
> 
> ve size yardımcı olabilmemiz için çalıştırdığınız GAM komutu gibi ayrıntıları ekleyin.

gam user <User Email Address> copy drivefile <Shared Drive ID> excludetrashed recursive copytopfolderpermissions false copyfilepermissions false copysubfolderpermissions false teamdriveparentid <Shared Drive ID>
