### ISSUE TITLE
Install script fails on linux-arm64 (browser_download_url for linux-arm64-glibc2.31.tar.xz version latest not found)

### ISSUE THREAD

**Issue by domdomegg** [GAM-team/GAM#1653]
Please confirm the following:
[x] I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
[x] I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Set up an ubuntu container on an Apple Silicon MacBook: `podman run --name gam -it ubuntu /bin/bash` (or equivalent docker: `docker run --name gam -it ubuntu /bin/bash`)
2. Install dependencies (inside container): `apt update && apt install curl python3 xz-utils -y`
3. Run install script (inside container): `bash <(curl -s -S -L https://gam-shortn.appspot.com/gam-install)`

Expected outcome (what are you trying to do?):
gam is installed correctly

Actual outcome (what errors or bad behavior do you see instead?):
```
This Linux distribution uses glibc 2.35
Check:2.31
Using GAM compiled against glibc2.31

Checking GitHub URL https://api.github.com/repos/GAM-team/GAM/releases for latest GAM release (unauthenticated)...

Getting file and download URL...

ERROR: Attribute: browser_download_url for linux-arm64-glibc2.31.tar.xz version latest not found
```

**Comment by domdomegg** [comment]
Temporary workaround: run container with x86_64 architecture using `podman run --name gam --platform=linux/x86_64 -it ubuntu /bin/bash`

**Comment by jay0lee** [comment]
There was an issue in the install script. Can you retry now?

**Comment by domdomegg** [comment]
Retried again, and this appears fixed. Thanks for the very fast turnaround! It now successfully installs. Full successful logs:

```
This Linux distribution uses glibc 2.35
Check:2.31
Using GAM compiled against glibc2.31

Checking GitHub URL https://api.github.com/repos/GAM-team/GAM/releases for latest GAM release (unauthenticated)...

Getting file and download URL...

Downloading file gam-6.58-linux-aarch64-glibc2.31.tar.xz from https://github.com/GAM-team/GAM/releases/download/v6.58/gam-6.58-linux-aarch64-glibc2.31.tar.xz to /tmp/tmp.iR9Ro7NGJT (unauthenticated)...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16.8M  100 16.8M    0     0  7180k      0  0:00:02  0:00:02 --:--:--  9.8M
Extracting archive to /root/bin

Finished extracting GAM archive.

Adding gam alias to profile file /root/.bashrc.

Can you run a full browser on this machine? (usually Y for MacOS, N for Linux if you SSH into this machine) n

GAM is now installed. Are you ready to set up a Google API project for GAM? (yes or no) n

You can create an API project later by running:

gam create project

Here's information about your new GAM installation:

GAM 6.58 - https://jaylee.us/gam - pyinstaller
Jay Lee <jay0lee@gmail.com>
Python 3.11.3 64-bit final
google-api-python-client 2.86.0
Linux Ubuntu 22.04 Jammy Jellyfish aarch64
Path: /root/bin/gam
```
