### ISSUE TITLE
$title > ERROR: invalid argument (Secondword) for account organization details

### ISSUE THREAD

**Issue by pierredagorn** [GAM-team/GAM#1659]
**Is your feature request related to a problem? Please describe.**
Hello, I'm trying to set some variable in a bash script then run :
gam create user $email firstname $firstname lastname $lastname organization title $title primary

But I've got the following error :
ERROR: invalid argument (Secondword) for account organization details
This happen only if my variable title is "Firstword Secondword"
It doesn't happen when I run the command line with the string within quotes directly like this
... organization title "Firstword Secondword" primary

**Describe the solution you'd like**
I would like a way to pass a multiple word jobtitle without gam thinking the secondword is an argument to organization instead of "primary"

**Describe alternatives you've considered**
Make all my jobtitle as one word with underscore

**Comment by taers232c** [comment]
Tr y:
gam create user $email firstname "$firstname" lastname "$lastname" organization title "$title" primary

Ross
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
This is bash expanding "Firstword Secondword" to two separate arguments. GAM has no way of knowing you meant it as one argument. Try:

```
gam create user "$email" firstname "$firstname" lastname "$lastname" organization title "$title" primary
```

quoting each of the variables ensures that Bash sees the variable value as a single bash argument even if there is a space in the value.

**Comment by pierredagorn** [comment]
Thank you it worked! I've been looking too far on this one.
