### ISSUE TITLE
error "End date greater than LastReportedDate" when trying to generate a report

### ISSUE THREAD

**Issue by moemilan** [GAM-team/GAM#1661]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
Yes, I am running the latest GAM version **GAM 6.58**
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
`gam report users`

Full steps to reproduce the issue:
1. run `gam report users user <email>`

Expected outcome (what are you trying to do?):
Get a user  data report without specifying a date as the GAM default behavior is to pull the most recently available report from Google
Actual outcome (what errors or bad behavior do you see instead?):
ERROR: End date greater than LastReportedDate

**Comment by taers232c** [comment]
Mohamed,

Google made an unannounced API change that caused this problem. They were supposed to revert the change.
Are you still seeing the error?

Ross
----
Ross Scroggs
***@***.***

**Comment by samuel-sobrino** [comment]
Hi, in my case yes I'm still getting this error
I was able to manage in other ways, so we'll wait and see.

**Comment by samuel-sobrino** [comment]
Seems to be resolved now

**Comment by moemilan** [comment]
Yes, I am running the command now without any issues and receiving the expected outcome.
