### ISSUE TITLE
"Delete User Other Contacts" broken?

### ISSUE THREAD

**Issue by bmcdonnell-scb** [GAM-team/GAM#1664]
### Please confirm the following
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
`Yes`
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
`Yes` (EDIT: copy/pasted)

### Full steps to reproduce the issue
1. Install & configure GAM (6.58)
2. Run `gam user user@domain.com delete othercontacts emailmatchpattern "*@olddomain.com"`. (Substitute `user@domain.com` and `olddomain.com` per your configuration.)

### Expected outcome (what are you trying to do?)
Expected to "Delete a selection of Other Contacts", [per the wiki](https://github.com/GAM-team/GAM/blob/main/docs/Users-People-Contacts-Profiles.md#delete-user-other-contacts), e.g.

```
gam user user@domain.com delete othercontacts emailmatchpattern "test.*"
Getting all Other Contacts for user@domain.com
Got 15 Other Contacts...
User: user@domain.com, Delete maximum of 15 Other Contacts
  User: user@domain.com, Other Contact: otherContacts/c2813750813749807666, Deleted
  User: user@domain.com, Other Contact: otherContacts/c7887232007947329156, Deleted
  User: user@domain.com, Other Contact: otherContacts/c523029179688316095, Deleted
  User: user@domain.com, Other Contact: otherContacts/c4889739431064427541, Deleted
  User: user@domain.com, Other Contact: otherContacts/c6318452176100245073, Deleted
```

### Actual outcome (what errors or bad behavior do you see instead?)

Deletion fails with error message:

`ERROR: othercontacts is not a valid argument for "gam <users> delete"`

**Comment by taers232c** [comment]
Gam 6.58 has no support for contacts, you need Advanced GAM.
See: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM <https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM>

Ross
----
Ross Scroggs
***@***.***

**Comment by bmcdonnell-scb** [comment]
@taers232c

> Gam 6.58 has no support for contacts

Why are unsupported standard GAM commands (such as this one) included in the standard GAM wiki ([link for this one](https://github.com/GAM-team/GAM/blob/main/docs/Users-People-Contacts-Profiles.md#delete-user-other-contacts))?

**Comment by bmcdonnell-scb** [comment]
As @taers232c suggested, I was able to execute this command using [GAMADV-XTD3](https://github.com/taers232c/GAMADV-XTD3/). (Thanks for that.)

But this is apparently still an issue for (this) standard GAM. Unless I've misunderstood the relationship between (this) standard GAM and GAMADV-XTD3, and for some reason the commands for both are mixed into this one's wiki?

**Comment by taers232c** [comment]
Here is the Standard GAM Wiki: https://github.com/GAM-team/GAM/wiki <https://github.com/GAM-team/GAM/wiki>

Please show me the page in that wiki that memtions contacts.
----
Ross Scroggs
***@***.***

**Comment by bmcdonnell-scb** [comment]
Here is the [link again to the wiki page in this repo that describes the command I'm referring to](https://github.com/GAM-team/GAM/blob/main/docs/Users-People-Contacts-Profiles.md#delete-user-other-contacts). This repo is for standard GAM, right?

Oddly, I see that there are several pages about Advanced-Gam/GAMADV-XTD3 in [this repo's docs folder](https://github.com/GAM-team/GAM/tree/main/docs)...?

**Comment by taers232c** [comment]
That's in the repo, not in the Wiki. Standard GAM is in the process of merging with Advanced GAM and the Wiki pages live there.
----
Ross Scroggs
***@***.***

**Comment by bmcdonnell-scb** [comment]
Ah.

> Standard GAM is in the process of merging with Advanced GAM and the Wiki pages live there.

Glad to hear you've working towards clarifying things. I'll defer to you as to whether/when to close this issue.

Thanks for your help.
