### ISSUE TITLE
GAM show imap doesn't list the usernames

### ISSUE THREAD

**Issue by aseques** [GAM-team/GAM#1665]
Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. I am trying to get the report of imap configuration for our users with the command form the [wiki](https://github.com/GAM-team/GAM/wiki/ExamplesEmailSettings#retrieving-imap-settings) 
`gam all users show imap<br>`

Expected outcome (what are you trying to do?):

I would expect a list of user -> attributes (any format is fine but the command is show only)

Actual outcome (what errors or bad behavior do you see instead?):

```
$ gam all users show imap
Getting all Users in Google Workspace account (may take some time on a large account)...
Got 148 Users...
done getting 148 Users.
 enabled: False
 autoExpunge: True
 expungeBehavior: archive
 maxFolderSize: 0
 enabled: False
 autoExpunge: True
 expungeBehavior: archive
 maxFolderSize: 0
 enabled: False
 autoExpunge: True
 expungeBehavior: archive
 maxFolderSize: 0
...
```

About the GAM release:

```
$ gam version 
GAM 6.58 - https://jaylee.us/gam - pyinstaller
Jay Lee <jay0lee@gmail.com>
Python 3.11.3 64-bit final
google-api-python-client 2.86.0
Linux Ubuntu 20.04 Focal Fossa x86_64
Path: /home/user/bin/gam
```

**Comment by taers232c** [comment]
The command is broken.

This works quite well in Advanced GAM
See: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM <https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM>

Ross
----
Ross Scroggs
***@***.***

**Comment by aseques** [comment]
It took a bit until I could test it, but I can confirm it work as expected
with the advanced gam, thanks a lot

Missatge de Ross Scroggs ***@***.***> del dia dv., 27 d’oct.
2023 a les 16:21:

> The command is broken.
>
> This works quite well in Advanced GAM
> See:
> https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM
> <
> https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM>
>
>
> Ross
> ----
> Ross Scroggs
> ***@***.***
>
>
>
