### ISSUE TITLE
Token has been expired or revoked.

### ISSUE THREAD

**Issue by mtwillis1965** [GAM-team/GAM#1666]
If you need help with GAM, please do not file an issue here, it will be closed and ignored.

Please post your question to the GAM discussion group where other admins are ready and willing to help:

https://groups.google.com/g/google-apps-manager

**Comment by mtwillis1965** [comment]
When running a GAM command - gam info user mtwillis@philasd.org  I get the followin error -  Authentication Token Error - ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})

This worked up until 10/23/23 after Google made the changes that we have to trust client-ids and apps etc. 

I have trusted my client-id for this project.   how do I make it work with having to create a new project

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Authorization#introduction <https://github.com/taers232c/GAMADV-XTD3/wiki/Authorization#introduction>

Scroll down to : Verify whether the super admin you'll be using is in an OU where reauthentication is required

Follow the directions and then do:
gam oauth delete
gam oauth create

Ross
----
Ross Scroggs
***@***.***

**Comment by mtwillis1965** [comment]
Ross,

Thanks so much that worked

Thanks again

Mark Willis, PMP
Senior IT Project Manager
School District of Philadelphia
(215) 400-5031



https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/36561610?key=522b60e90633bda83a700ed65361e07eccbdb2272e18993024bfcdfd435ecfd2



*Click **here*
<https://philasd.co1.qualtrics.com/jfe/form/SV_6SiweqqjqE7deT3?Source=EMAILIT&Office=Office%20of%20Information%20Technology%20and%20Data%20Management>*
<https://philasd.co1.qualtrics.com/jfe/form/SV_6SiweqqjqE7deT3?Source=EMAILIT&Office=Office%20of%20Information%20Technology%20and%20Data%20Management>to
*

*tell us how we are doing!*


Any Questions? Please call the I.T. Help Desk at 215-400-5555 or email
at ***@***.***
***@***.***>.*


Visit *philasd.org/technology <http://philasd.org/technology>* for more
information.


Visit *sishelp.philasd.org <http://sishelp.philasd.org/>* for SIS training
resources.
