### ISSUE TITLE
ERROR: projection is not a valid argument for "gam info browser"

### ISSUE THREAD

**Issue by ropelletier** [GAM-team/GAM#1667]
Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* Yes, new install
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
* Yes

Full steps to reproduce the issue:
1. run "gam info browser idofbrowser projection FULL"

Expected outcome (what are you trying to do?):
Get more information, specifically the profiles information

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: projection is not a valid argument for "gam info browser"

**Comment by taers232c** [comment]
The documentation is incorrect, drop the word projection
> gam info browser idofbrowser  FULL

Ross
----
Ross Scroggs
***@***.***
