### ISSUE TITLE
Vault support for Calendar

### ISSUE THREAD

**Issue by jay0lee** [GAM-team/GAM#1669]
Vault API now supports Calendar exports. See:

https://github.com/jay0lee/google-api-tracker/commit/2c901a883806a8751125058cf6f497a927954702#diff-021f24c148bc4de4ad05784b8285510597d7d17b0fb4756ed3443b241b47c817

Add GAM support for these export methods.

@taers232c fyi

**Comment by taers232c** [comment]
Will do
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
@taers232c I believe support has been added here? If so maybe link to the commit and then let's close this issue out.

**Comment by taers232c** [comment]
This was added in 6.67.00.
