### ISSUE TITLE
Creating user delegate fails silently

### ISSUE THREAD

**Issue by danny-waite** [GAM-team/GAM#1674]
Full steps to reproduce the issue:
1. Fresh install of GAM
2. Issue `gam user x add contactdelegate y`
3. Check with `gam all users print delegates`

Expected outcome (what are you trying to do?):
Delegate should be created

Actual outcome (what errors or bad behavior do you see instead?):
The `add contactdelegate` appears to work, no error messages reported but does not show up in `gam all users print delegates`

`check serviceaccount` shows all success

**Comment by jay0lee** [comment]
Closing this as others have not reported issues and there are no updates here.

If you are still seeing issues feel free to reach out via git.io/gam-group or git.io/gam-chat or re-open this issue.
