### ISSUE TITLE
"show drivefileacl" out to csv

### ISSUE THREAD

**Issue by bennettjdMPS** [GAM-team/GAM#1676]
I am trying to script out a way to get the users shared drives and then show how the user has permission to the shared drive. I can get the list of shared drives (using "print shareddrives") and that output is via csv. I then suck that in and is going through a foreach loop to get the drivefileacl function but this is just listed as text and not a csv. It would be great if it was a csv so then I could output the fields that I need like email address and role. I use PowerShell to work with gam for for the scripting needs.

**Comment by taers232c** [comment]
Joshua,

Send me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***
