### ISSUE TITLE
Product License for Gemini Business for Google Workspace, Gemini Enterprise for Google

### ISSUE THREAD

**Issue by pheeraphonglek** [GAM-team/GAM#1680]
**Is your feature request related to a problem? Please describe.**
Google has new product 'Gemini Business for Google Workspace, Gemini Enterprise for Google'
**Describe the solution you'd like**
GAM should assign the new product license to the user.
**Describe alternatives you've considered**
I have to assign by manually. It takes too much time.
**Additional context**

**Comment by taers232c** [comment]
What is: gam version

If it is 6.58 you'll have to upgrade to Advanced GAM; it supports those licenses.

See: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM

Ross
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
These SKUs are added in recent versions of GAM. Also if you know the productId  / skuId you can always manually specify them on the command.
