### ISSUE TITLE
ERROR_ Internal 

### ISSUE THREAD

**Issue by marxoa** [GAM-team/GAM#1683]
Hello, when trying to install gam in the permissions part it gives me this error

![image](https://github.com/GAM-team/GAM/assets/77907022/6a4814a7-af92-401d-9db2-9a18a7eb8e99)
![image](https://github.com/GAM-team/GAM/assets/77907022/d8c14809-7cf4-43c2-8a90-31d9fdb28096)

**Comment by taers232c** [comment]
Other users have been experiencing this error today, Google broke something.

All you can do is to keep trying.

Ross
----
Ross Scroggs
***@***.***

**Comment by marxoa** [comment]
I managed to repair it by opening the link on another PC, but now when I try to send an email it gives me this error

![image](https://github.com/GAM-team/GAM/assets/77907022/73dcf5c6-5dcc-4445-9bb9-01f0fce1773c)

**Comment by taers232c** [comment]
Do: gam user ***@***.*** ***@***.***> check serviceaccount

Ross
----
Ross Scroggs
***@***.***
