### ISSUE TITLE
GAM Install Product Information

### ISSUE THREAD

**Issue by OldManWindowsGuy** [GAM-team/GAM#1689]
**Is your feature request related to a problem? Please describe.**

When installing GAM, we noticed under Programs and Features in Windows, that the Publisher information appears to be "Jay Lee - Jay0Lee@gmail.com".  Can this be updated to a more official publisher information?  We were told to use this by Google Representatives for what we cannot accomplish in our Google Admin Console.  The issue, in our enivironment, this will show up like a sore thumb in security scans and appear as possible malicious software or codes.  If it could be replaced with Google, Inc. or even GAM, Inc that would be better.

![GAM-Installed](https://github.com/GAM-team/GAM/assets/171264888/d237fe14-b52e-4149-a555-09410b5822c3)

**Describe the solution you'd like**

An official Publisher name that doesn't make it look like a HomeBrew app or malware.

**Describe alternatives you've considered**

None available, can't do some of what is needed in the console, only way to script or automate things.

**Additional context**

**Comment by taers232c** [comment]
GAM is open source software, Jay Lee is the publisher, that's official.

Ross
----
Ross Scroggs
***@***.***

**Comment by OldManWindowsGuy** [comment]
Nothing like a good old, we will do nothing.  Thanks for the consideration.

**Comment by jay0lee** [comment]
@OldManWindowsGuy please be considerate of Ross, he dedicates an enormous amount of time to this project and claiming he does nothing is just ignorant.

Ross' statement is correct. GAM is NOT a Google product, it's an open-source tool that calls Google APIs.

**Comment by OldManWindowsGuy** [comment]
I think it's a poor response to asking for a better Publisher name to be listed on the app installed than a Gmail account.   I think he should be considerate as well when responding to messages and ending it with, that's official.  It was an immediate, no further discussion on the subject.

**Comment by taers232c** [comment]
I apologize if my reply came off as curt.
Jay is the author of Standard GAM and I am the author of Advanced GAM.
These are open source projects maintained by us as individuals.
What other publisher information could there be?

Ross

----
Ross Scroggs
***@***.***
