### ISSUE TITLE
GAM Export to CSV

### ISSUE THREAD

**Issue by OldManWindowsGuy** [GAM-team/GAM#1690]
**Is your feature request related to a problem? Please describe.**

When exporting GAM information to CSV, it combines everything in the first column.  Splitting by the "," is not a great option and often doesn't work.  The only way I have found to fix this issue is by re-importing the export and then re-exporting using Powershell.  A better way to export to CSV and see your information would be better.
![GAM-Export-CSV](https://github.com/GAM-team/GAM/assets/171264888/d40a8d95-35b5-4728-a2a0-e50edcc81fbc)

Commands I am using to fix this:

#Exports the data
GAM Print CROS allfields > C:\GAM\Exports\GAM-Devices.csv

Using Powershell to re-import so I can export again and each column appear in it's own column
$GAMDevices = import-csv C:\GAM\Exports\GAM-Devices.csv
$GAMDevices | Export-csv c:\GAM\Reports\$GAM-Devices-Formatted-Correctly.csv

**Describe the solution you'd like**

Better Export to CSV Funcationality.  Opening a CSV and all the data is in the first column is frustrating.

**Describe alternatives you've considered**

Better Export to CSV Funcationality.  Opening a CSV and all the data is in the first column is frustrating.

**Additional context**

**Comment by taers232c** [comment]
A CSV file has columns separated by commas which is what GAM produces.
The program that reads the CSV files needs to interpret the comma as a column separator.
Try: $GAMDevices = import-csv C:\GAM\Exports\GAM-Devices.csv -Delimiter ,

Ross
----
Ross Scroggs
***@***.***

**Comment by OldManWindowsGuy** [comment]
Sorry, you misunderstood my comment.  The export to CSV is the issue.  Not the re-importing which fixes the formatting and exporting.

Microsoft Excel is the program I am using to review it, it's all mashed in 1 line and column if I don't use Powershell to fix the formatting....

**Comment by OldManWindowsGuy** [comment]
#Exports the data and results in Excel reading all the data in 1 Column
GAM Print CROS allfields > C:\GAM\Exports\GAM-Devices.csv

Using Powershell to re-import so I can export again and each column appear in it's own column
$GAMDevices = import-csv C:\GAM\Exports\GAM-Devices.csv

Again, when I use Powershell above to re-import into a variable called $GAMDevices, I can export it and it be properl formatted for a spreadsheet program to open the data and each source, in its own Column.

$GAMDevices | Export-csv c:\GAM\Reports\GAM-Devices-Formatted-Correctly.csv

So the issue, is literally the export Piping command to CSV above "GAM Print CROS allfields > C:\GAM\Exports\GAM-Devices.csv".  I can only fix the formatting by the re-import and export using Powershell.  This ">" to csv is just piping it out and doesn't do a great job.

**Comment by taers232c** [comment]
The export to the CSV is not the issue, it's Excel. When you import a CSV file info Excel, you have to tell it that the column delimiter is comma, it often defaults to tab.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation and I'll help.

ross.scroggs @ gmail.com <http://gmail.com/>

Ross
----
Ross Scroggs
***@***.***

**Comment by daethnir** [comment]
I'm a unix and mac user, and gam generates valid CSVs 100% of the time. I load them in excel, in google sheets, etc. Have never seen this problem.

Sounds like it's the issue ross already described, or possibly the file has unix (\n) line endings and your excel is expecting windows (\r\n) endings and getting cranky.

**Comment by OldManWindowsGuy** [comment]
Must be as Daethnir said, it's not that it's not generating a CSV.  It does do that.  But depending on your Spreadsheet tool, Excel doesn't read it without manually having to tell Excel what the eliminator is each time.  Powershell Export-CSV doesn't have this issue the GAM export has and can export to csv just fine and excel open it with it all in its own columns.

Looks like the solution is probably just to add time to my script, export from GAM and use Microsoft to fix the CSV in Excel.

**Comment by taers232c** [comment]
What is: gam version
----
Ross Scroggs
***@***.***

**Comment by OldManWindowsGuy** [comment]
GAM version is 6.58

**Comment by taers232c** [comment]
You have standard GAM, it have no ability to change the comma to some other character.
With Advanced GAM, yu can specify that you want tab (for example) to be the column delimiter.

Upgrading is easy: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM

You would then do:

gam redirect csv C:\GAM\Exports\GAM-Devices.csv columndelimiter "\t"  Print CROS allfields 

Ross
----
Ross Scroggs
***@***.***

**Comment by OldManWindowsGuy** [comment]
Actually, looking at the Text Output of the CSV file.  I think I see why Microsoft Excel is not delimiting it automatically.  The GAM export using > to CSV is not encapsulating the information in quotes (i.e. "deviceid", "activeTimeRanges.o.activeTime","serialnumber" and instead is doing this deviceid, activeTimeRanges.o.activeTime,serialnumber).  Powershell must be auto delimiting on the "," and excel is doesn't like that, because a comma alone could be in the cell.  So just dumps into 1 column.  

If the GAM tool could export this information quoted, that would probably resolve the Excel Issue seeing it and forcing you to define the delimitor when opening.  Which doesn't work in excel due to some sort of word wrapping.  

Take a model information field like this: ASUS Chromebook Flip C214 (EDU), ASUS Chromebook Flip C234 (CANADA CONSUMER) found in the report, having to define when you open the spread sheet, throws off all the columns.  

See the output, the top is done by Powershell Export to CSV, which quotes the fields for better delimitation.

![GAM-Export-CSV-vs-GAM-ExportCSV](https://github.com/GAM-team/GAM/assets/171264888/f844eb38-91dd-40da-beab-ff86bf4e1beb)

**Comment by OldManWindowsGuy** [comment]
Further analysis, it does quote it, but only when the field itself does contain a ",".  so it would be great if this could be updated to always quote "" the data and fields.  Then this would work and have no issues in Excel.

![GAM-Export-Format](https://github.com/GAM-team/GAM/assets/171264888/c9e5b1da-f814-4597-a2e3-9a21750da503)

**Comment by daethnir** [comment]
The CSV spec does have rules about when quotes are needed (e.g. a field contains the separator character) but they are not needed except in those cases.

Adding them to every field would add needless overhead; this should not be done, the file is already valid CSV until proven otherwise.

**Comment by erkram** [comment]
MS Excel is designed to behave this way.  See Microsoft Community post [CSV
excel sheets do not open in columns](
https://answers.microsoft.com/en-us/msoffice/forum/all/csv-excel-sheets-do-not-open-in-columns/cc16bead-9efb-445e-b0ea-b1abf7e60e30)
for more information.

Erik

**Comment by OldManWindowsGuy** [comment]
Thank you, I understand how to Delimit a file in Excel using that feature.  What I am saying, that doesn't work for the output provided by the GAM tool.....

After manually delimiting on the ",".  I has what should be Columns, showing as rows.... The first 8 rows, are actually supposed to be columns if this was delimiting correctly....

![Excel-Not-Able-To](https://github.com/GAM-team/GAM/assets/171264888/2bd880b2-ef2c-4084-b026-8e103cd09cea)

**Comment by OldManWindowsGuy** [comment]
I missed the check box for the headers, but again. this is the problem with manual delimitors.  But it doesn't sound like this is a feature that can be fulfilled as its been determine to be too much over head.

I will use Powershell to re-import the file and correct the issues.  Just create more overhead for my script.  

Thanks for the consideration.  It would help windows admins out some trying to use this tool and for things we can't do in the console.

**Comment by taers232c** [comment]
GAM is producing a valid, correctly delimited CSV (Comma Separated Values) file. 
The fact that Excel can't read it correctly by default is Excel's problem.

Send me a Meet/Zoom invitation if you'd like to discuss.

Ross
----
Ross Scroggs
***@***.***

**Comment by OldManWindowsGuy** [comment]
We can close this feature request, I was hoping to improve the export.  I was hoping the product could be updated to work more seamlessly with other products like Excel.

Thanks for the consideration.

**Comment by taers232c** [comment]
See: https://superuser.com/questions/606272/how-to-get-excel-to-interpret-the-comma-as-a-default-delimiter-in-csv-files

Ross
----
Ross Scroggs
***@***.***

**Comment by OldManWindowsGuy** [comment]
This is not so much about opening it in excel and being able to review it.  But really more about using another scripting tool to wrap around the GAM Export.  The GAM tool itself is not much useful without being able to build a script and automation around it to do what you want.

Even PowerShell, doesn't recognize the data dumped into a variable as an Array of data with columns.  It's one large set with no ability to filter on the individual columns.  I've have tried adding the @(), splitting it out etc.  Below is about the only thing I found to make it work. Export it, re-import it to a new variable.  I'd like to have just dumped into a variable and be able to manipulate as needed.  

$MyVariable = GAM Print CROS allfields

$MyVariable.SerialNumber

This should just provide me a list of SerialNumbers....  But it doesn't because it doesn't recognize it correctly.

So instead, I have dump it out to a CSV file first:
GAM Print CROS allfields > C:\GAM\Exports\GAM-Devices.csv

Then re-import that CSV
$MyNewVariableImport = import-csv C:\GAM\Exports\GAM-Devices.csv

To be able to use the individual column members
$MyNewVariable.SerialNumber

I closed the Feature Request; I'll deal with the overhead on my script side.  I just figured it would be something simple to fix on the coding side (even a command switch to change the CSV output).  But I will code it on my end instead.

![Script](https://github.com/GAM-team/GAM/assets/171264888/d16dd270-812a-458f-982a-22ec1fde977c)

**Comment by taers232c** [comment]
Again, with Advanced GAM you can choose whatever column delimiter character you'd like.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
With Advanced GAM, you can also direct the output directly to a Google Sheet.

Ross
----
Ross Scroggs
***@***.***

**Comment by OldManWindowsGuy** [comment]
I'll give it a try

**Comment by taers232c** [comment]
I'm available right now (it's about 6:30PM PDT) or in the morning from 6:30 to 7:30.

If you'd like hekp, send a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***

**Comment by paulmiglio** [comment]
> This is not so much about opening it in excel and being able to review it. But really more about using another scripting tool to wrap around the GAM Export. The GAM tool itself is not much useful without being able to build a script and automation around it to do what you want.
> 
> Even PowerShell, doesn't recognize the data dumped into a variable as an Array of data with columns. It's one large set with no ability to filter on the individual columns. I've have tried adding the @(), splitting it out etc. Below is about the only thing I found to make it work. Export it, re-import it to a new variable. I'd like to have just dumped into a variable and be able to manipulate as needed.
> 
> $MyVariable = GAM Print CROS allfields
> 
> $MyVariable.SerialNumber
> 
> This should just provide me a list of SerialNumbers.... But it doesn't because it doesn't recognize it correctly.
> 
> So instead, I have dump it out to a CSV file first: GAM Print CROS allfields > C:\GAM\Exports\GAM-Devices.csv
> 
> Then re-import that CSV $MyNewVariableImport = import-csv C:\GAM\Exports\GAM-Devices.csv
> 
> To be able to use the individual column members $MyNewVariable.SerialNumber
> 
> I closed the Feature Request; I'll deal with the overhead on my script side. I just figured it would be something simple to fix on the coding side (even a command switch to change the CSV output). But I will code it on my end instead.
> 
> ![Script](https://private-user-images.githubusercontent.com/171264888/335399082-d16dd270-812a-458f-982a-22ec1fde977c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTc4MTQsIm5iZiI6MTcxNzE1NzUxNCwicGF0aCI6Ii8xNzEyNjQ4ODgvMzM1Mzk5MDgyLWQxNmRkMjcwLTgxMmEtNDU4Zi05ODJhLTIyZWMxZmRlOTc3Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMjExNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDFiYzIzNzhkZTA3NDhlMWY5ZDI0NDNmYjYzZDhlMzQ1ZmJjNmQxYzlhOTg3NmZkNDYwNTRlYjkyZjY1NjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C3r8FiHoctl56tVkrZmRIRIvoCUJHcTk7tr2wBK4xl8)

I’ve been doing this exact thing for a few years now. Same reason. Let me know if you find a better way.

**Comment by taers232c** [comment]
How about:

$MyVariable = GAM Print CROS allfields | ConvertFrom-Csv -Delim ','

Ross
----
Ross Scroggs
***@***.***
