### ISSUE TITLE
Blank Fields in CSV file dump chrome devices to the base OU

### ISSUE THREAD

**Issue by undeadrattler** [GAM-team/GAM#1692]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Create a CSV file with asset and ou columns.
2. Place a blank entry into either column.
3. Run `gam csv test.csv gam update cros "query:asset_id:'~~asset~~'" ou '~~ou~~'`

Expected outcome (what are you trying to do?):
Gam will update things that have information in the fields, and error out/not find a device or OU on things that don't.

Actual outcome (what errors or bad behavior do you see instead?):
Gam will take the specified device and dump it in the base OU, and dump _all_ devices in the base OU.

some small troubleshooting shows that `gam print cros query "asset_id:''"` will select _every device_ in the organization, and `gam info org ''` will select the base OU.

`gam print cros query "asset_id:' '"` will also select every device, but `gam info org ' '` will return with OU not found.

I understand that a blank is specified by using the single quotes, but why does a blank input return everything or default to the base OU instead of erroring out?

**Comment by taers232c** [comment]
This can be handled with Advanced GAM, send me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***

**Comment by undeadrattler** [comment]
I think you may have misunderstood - I have used this successfully in the past with a CSV that did not have blank lines. I updated a sheet I use and had a couple devices that I missed putting the OU in and a couple devices that I hadn't assigned asset tags to yet.

The expected result would be that those get skipped instead of moving every device in my organization to the base OU.

Unless Advanced Gam has an undo button somewhere, I've got a bit of manual cleanup to do.
I wanted to forewarn others and see if that's intended behavior, not look for advice :)

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation

Ross
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
closing this but if there are still issues feel free to discuss on the GAM group or chat.
