### ISSUE TITLE
Mass updating user phone number and location with CSV

### ISSUE THREAD

**Issue by Mingll0** [GAM-team/GAM#1694]
I have tried putting:
gam csv upsig.csv gam update user ~email phone type ~type value ~ext organization location ~room

And
gam csv upsig.csv gam update user ~email phone type "~type" value "~ext" organization location "~room"

With the corresponding heading naming after the "~"

But it still comes back with Invalid argument.
I tried with the similar syntax to mass create user with their first name , last name, password and there is no problem. 
I suspect I got the phone type and value incorrectly and also tried with primary phone type but still no go.

Any help is appreciated.

**Comment by taers232c** [comment]
<UserAttribute> ::=
...
        (organization [type domain_only|school|unknown|work] [customtype <String>]
                [name <String>] [title <String>] [department <String>]
                [symbol <String>] [costcenter <String>] [location <String>]
                [description <String>] [domain <String>]
                [fulltimeequivalent <Integer>]
		notprimary|primary)|
	(phone [type assistant|callback|car|company_main|grand_central|home|
                home_fax|isdn|main|mobile|other|other_fax|pager|radio|telex|tty_tdd|
                work|work_fax|work_mobile|work_pager|(custom <String>)]
                [value <String>]
                notprimary|primary)|

You're missing the required keyword notprimary|primary

> gam csv upsig.csv gam update user ~email phone type ~type value ~ext primary organization location ~room primary
> 

> gam csv upsig.csv gam update user ~email phone type "~type" value "~ext" primary organization location "~room" primary
> 

Ross

----
Ross Scroggs
***@***.***

**Comment by Mingll0** [comment]
Works like a charm! Thanks Ross!
