### ISSUE TITLE
Trying to add CustomAttribute vallue getting an error. 

### ISSUE THREAD

**Issue by iabud-24** [GAM-team/GAM#1695]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/GAM-team/GAM/wiki

Full steps to reproduce the issue:
I have created two Custom attributes 
    1>> Category: AzureAD, Name: ImmutableID , Info type: text, Visibility: Visible to user and admin No of Value: Single Value.
    I have used this cmdlet to add the value (gam update user user@domain.org AzureAD.ImmutableID ZNnP9o/CHUSCtrdse7fgCw==) this command works perfectly. 
     2>>a) Category: Enhanced desktop security, Name: Local windows accounts, Info type: text, Visibility: Visible to user and admin No of Value: Multi Value.
            b) Category: AD accounts, Name: Local windows accounts, Info type: text, Visibility: Visible to user and admin No of Value: Multi Value.

for this I have tried below formats 
*gam update user user@domain.org "Enhanced desktop security.AD accounts" Domain.org\UPN
*gam update user user@domain.org "Enhanced_desktop_security.AD_accounts" Domain.org\UPN

Error: ERROR: 400: Invalid Input: custom_schema - invalid

So I hope there is something missing, would it be possible to get the right cmdlet.

**Comment by taers232c** [comment]
Do: gam show schemas

I believe that you want the following but seeing the schemas will help.
> *gam update user ***@***.*** ***@***.***> "Enhanced_desktop_security.Local_windows_accounts" Domain.org\UPN
> *gam update user ***@***.*** ***@***.***> "AD_accounts:Local_windows_accounts" Domain.org\UPN
> 
Ross

----
Ross Scroggs
***@***.***

**Comment by iabud-24** [comment]
Hello,

see below schema's

C:\Windows\system32>gam show schemas
Schema: AzureAD
 schemaId: 3y8R8zOfQG-UtXsoeMbUyQ==
 displayName: AzureAD
 Field: ImmutableID
  fieldId: KJupEVoAR8y1YhJ5W4POxw==
  fieldType: STRING
  displayName: ImmutableID
  multiValued: False
  readAccessType: ADMINS_AND_SELF
Schema: Enhanced_desktop_security
 schemaId: Md6sNo8VQCSSoYWaXx2WPA==
 displayName: Enhanced desktop security
 Field: Local_windows_accounts
  fieldId: sg86RjVXQwC-GBVEi-hMkw==
  fieldType: STRING
  displayName: Local windows accounts
  multiValued: True
  readAccessType: ADMINS_AND_SELF
 Field: ADaccounts
  fieldId: vq3irX-nT7nQWsZ8WPtRyg==
  fieldType: STRING
  displayName: AD accounts
  multiValued: True
  readAccessType: ADMINS_AND_SELF

**Comment by taers232c** [comment]
<SchemaNameField> ::= <SchemaName>.<FieldName>
<UserBasicAttribute> ::=
...
<SchemaNameField> [multivalued [type home|other|work|(custom <String>)]] <String>


The last two custom schema fields are multivalued so you have to add an additional keyword

update AzureAD.ImmutableID xxx
update Enhanced_desktop_security.Local_windows_accounts multivalued xxx
update Enhanced_desktop_security.ADaccounts multivalued xxx

update Enhanced_desktop_security.Local_windows_accounts multivalued type work xxx
update Enhanced_desktop_security.ADaccounts multivalued type work xxx

Ross

----
Ross Scroggs
***@***.***
