### ISSUE TITLE
add custom attributes in bulk at  Google workspace admin console 

### ISSUE THREAD

**Issue by PranitaPingale92** [GAM-team/GAM#1698]
We need to add custom attributes as token for the SAML application in bulk. Additionally, I would like to know how to update these attributes when a new user joins. Manually adding these attributes can be time-consuming and inefficient.

How can i achieve this scenario .

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users#define-schema-fields

Ross
----
Ross Scroggs
***@***.***
