### ISSUE TITLE
GAM 7.0 project update (rotate private key)

### ISSUE THREAD

**Issue by bennettjdMPS** [GAM-team/GAM#1699]
I am trying to update to GAM 7 on windows. I used the gam update project and it was going through the 39 API's. At the bottom of the line it shows Service Account: gam-xxxxx@gam-xxx.iam.gserviceaccount.com, Giveing account gam-xxxxx@gam-xxx.iam.gserviceaccount.com rights to rotate gam-xxxxx@gam-xxx.iam.gserviceaccount.com private key. 
It then just goes back to PowerShell. I look at the permissions in the project and the service account is set to "Service Account Key Admin".

**Comment by jay0lee** [comment]
Please post this to the group:

git.io/gam-group
