### ISSUE TITLE
gam 6.58  use gam info course can show student  list , but gam 7.0 version cannot 

### ISSUE THREAD

**Issue by Benc1998** [GAM-team/GAM#1706]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://github.com/GAM-team/GAM/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam info course 
2. info can show stuents in verion 6.58 or older,  but version 7 is cannot
3.

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Classroom-Courses#display-courses

gam info course 690814266789 show students

Ross
----
Ross Scroggs
***@***.***

**Comment by Benc1998** [comment]
i see. thx your reply !!

Ross Scroggs ***@***.***> 於 2024年9月30日週一 上午8:33寫道：

> See:
> https://github.com/taers232c/GAMADV-XTD3/wiki/Classroom-Courses#display-courses
>
> gam info course 690814266789 show students
>
> Ross
> ----
> Ross Scroggs
> ***@***.***
>
>
>
