### ISSUE TITLE
[FR] Integrate the GAM ADVX-TD3 style Navigation / Documentation into GAM7

### ISSUE THREAD

**Issue by stephengale801** [GAM-team/GAM#1708]
**Is your feature request related to a problem? Please describe.**
The Legacy version of GAM is wonderful for it's examples and tutorials.  The Advanced version is great when it comes to documentation and structure.  Splitting the "Client access" and the "Service account access" sections makes it so much easier when attempting to help others understand the command structure and how requests are processed.

Moving from ADVX-TD3 to GAM7 feels like moving from Window 7 Pro to Windows 11 Home.  All of the advanced features are there, but you can't find the documentation as easily. 

**Describe the solution you'd like**
Bring over the Side navigation, Breakdown, and Documentation pages into the Wiki pages.  Leave the Tutorials in their own section, but bring over the BNF type syntax.

**Additional context**
ADVX-TD3 Wiki Navigation:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/5ff40f1a-8751-4626-b255-f0045b74887c">

GAM7 Wiki Navigation:
<img width="297" alt="image" src="https://github.com/user-attachments/assets/35d0ae96-d9d2-426f-b3fd-1ed0dff82ca9">

**Comment by jay0lee** [comment]
@taers232c I believe this is done now?

**Comment by taers232c** [comment]
Yes
