### ISSUE TITLE
Improve Error Messaging in GAM when user hits the max number of group memberships

### ISSUE THREAD

**Issue by wefanqs** [GAM-team/GAM#1710]
Issue: When attempting to add a user to a new Google Group using GAM, who has already exceeded the Gaia membership limit, the error message returned is not informative enough for effective troubleshooting.

Full steps to reproduce the issue:
1. A user is over the Gaia membership limit
2. Attempt to add this user to a new Google Group using GAM.
3. Observe the error message: ERROR: 412: Condition not met - conditionNotMet.
4. Compare with the Groups WebUI, which provides a more detailed error message: "An error occurred. 1 person has reached the maximum number of groups they can join. To be added to any new groups, they must leave some where they're currently a member."

Suggestion: It would be beneficial to align GAM’s error messaging with that of the Groups WebUI. Could GAM provide a detailed error message indicating that the user has reached their group membership limit? It will make the error more understandable and actionable.

**Comment by jay0lee** [comment]
Unfortunately GAM only knows what Google servers tell it about the problem. GAM has no knowledge of these limits or which condition Google may be referring to here.

Without Google providing a more meaningful error message on their end there's no way for GAM to determine where the error lies.
