### ISSUE TITLE
"UserWarning" in final step of "gam create project"

### ISSUE THREAD

**Issue by passCulture-JL** [GAM-team/GAM#1711]
GAM 7.00.16

`gam create project`

...
Project: ***, Service Account: ***, Extracting public certificate
**__init__.py:12382: UserWarning: Attribute's length must be >= 1 and <= 64, but it was 70
__init__.py:12383: UserWarning: Attribute's length must be >= 1 and <= 64, but it was 70**
Project: ***, Service Account: ***, Done generating private key and public certificate
...

**Comment by jay0lee** [comment]
@taers232c we should be OK reducing the project name. I'd keep the gam-project- prefix in case anyone is using a regex to identify GAM projects but reduce the # of random characters we append at the end.

**Comment by taers232c** [comment]
Fixed in 7.00.18.
