### ISSUE TITLE
Add an Ubuntu 24.04 build

### ISSUE THREAD

**Issue by jay0lee** [GAM-team/GAM#1712]
Today GAM builds on Ubuntu 22.04. Ideally for long term compatibility and deprecation goals we'd also be building on the latest Ubuntu 24.04 LTS. A 24.04 build should compliment the 22.04 build, not replace it. @taers232c fyi.

**Comment by jay0lee** [comment]
Also, rather than needing to maintain a list of glibc versions in gam-install.sh, we should switch to the new script that auto-detects the give glibc / legacy versions in a given GAM version release and uses them.

**Comment by taers232c** [comment]
I wasn't clear, I didn't replace 22.04, I added 24.04.
----
Ross Scroggs
***@***.***
