### ISSUE TITLE
ERROR: 403: Permission denied to enable service 

### ISSUE THREAD

**Issue by xmen2005** [GAM-team/GAM#1713]
Is this a new update from Google, or is it just an error?
I was surprised by this error in GAM when I tried to link it with an account.

 
![0000](https://github.com/user-attachments/assets/a56bf9c1-3cc3-4d13-8de4-3095727c2e3a)

**Comment by jay0lee** [comment]
Actually I heard of another case of this and it appears to be a Google internal issue. Please file a support ticket and reference Google Internal issue 373322918.

**Comment by xmen2005** [comment]
I tried to enable all APIs, but I didn’t get any results; I'm still facing the same issue 

I don't know

**Comment by jay0lee** [comment]
As mentioned above you'll need to put in a support ticket with Google.

**Comment by taers232c** [comment]
What was the resolution?
