### ISSUE TITLE
MSI upgrade is deleting some files in lib/

### ISSUE THREAD

**Issue by jay0lee** [GAM-team/GAM#1714]
Some admins are seeing that when upgrading the Windows MSI for GAM, they are left with an incomplete installation. Files are missing from lib/ and this causes GAM to crash with various missing files/libraries errors.

The issue seems to be that when we build the GAM MSI, heat.exe generates a new `Guid` ID for each file on each run. So the MSI installer sees them as unique files and for some reason fails to actually replace them.

We need a stable `Guid` for files across GAM MSI builds.

**Comment by jay0lee** [comment]
Workaround:

1) uninstall GAM7 MSI completely (gam.cfg and project files are NOT deleted).

2) install latest MSI.

That way we're not actually doing an upgrade and all files are copied.

More permanent fix incoming....

**Comment by jay0lee** [comment]
I've rewritten the tool script at:

https://github.com/GAM-team/GAM/blob/main/src/tools/gen-wix-xml-filelist.py

now after heat.exe runs the above script also runs and sets `Guid` to a uuid5 based on the source filename. That means that on every GAM MSI build a given filepath will get the same `Guid`.

This *should* fix MSI builds going forward but anyone with GAM 7.00.19 or older will need to do the uninstall, reinstall workaround at least once to get this solved.

**Comment by taers232c** [comment]
In the legacy version, uninstalling GAM did not delete the GAM folder; now it does.

Users should be warned abount storing any user files in that directory.

Ross
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
@taers232c do you know what change caused that? Ideally we would never delete files we didn't install. (and who really cares if c:\gam7 lives past MSI uninstall?)

**Comment by taers232c** [comment]
I just checked, if there are any user files in c:\GAM, the folder is not deleted
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
I'd call the new version 7.01.00 so it's easer to distinguish that this is the fixed version.

I have changes coming, I'll wait until you've got the issues resolved.

Ross
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
This should be resolved now. Closing.
