### ISSUE TITLE
OPENSSL_Uplink(00007FFD9D745A28,08): no OPENSSL_Applink

### ISSUE THREAD

**Issue by gabriel-depaula** [GAM-team/GAM#1717]
Full steps to reproduce the issue:
1. I installed the latest version of GAM 7.00.39, on a Windows 10 PRO
2. GAM was installed in the folder suggested by the installer C:\GAM7
3. All commands I try to run return the same error: OPENSSL_Uplink(00007FFD9D745A28,08): no OPENSSL_Applink

I also have version 6.58 of GAM installed on this same machine. And this version runs without any errors.

**Comment by jay0lee** [comment]
How did you install GAM? If You used the MSI can you try:

1) uninstalling GAM7 from Windows add/remove programs (your config and other files will not be deleted)
2) reinstall GAM via the MSI.

**Comment by gabriel-depaula** [comment]
Yes, I installed GAM through MSI. (gam-7.00.39-windows-x86_64.msi)
I tried uninstalling GAM as you suggested, through Windows add/remove programs.
Then I reinstalled GAM.
I tested it and the same problem happens: OPENSSL_Uplink(00007FFD9D115A28,08): no OPENSSL_Applink

I also tried doing a clean install. Uninstalling GAM and then completely removing the GAM7 folder.
And the same problem occurs.

**Comment by taers232c** [comment]
Try: gam-7.00.38-windows-x86_64.msi

Does that work?

Ross
----
Ross Scroggs
***@***.***

**Comment by gabriel-depaula** [comment]
I tested the following versions:
7.00.39
7.00.38
7.00.37
7.00.36
7.00.35

The same error occurs in all these versions.

**Comment by taers232c** [comment]
Jay, I don't see the link in your previous comment.

**Comment by jay0lee** [comment]
https://slicer.readthedocs.io/en/latest/user_guide/get_help.html#slicer-application-does-not-start

**Comment by jay0lee** [comment]
closing this, if you are still having issues please reach out on the group but I believe this may be due to conflicts with other apps installed on your system. You may need to clean that up as described in the link above.
