### ISSUE TITLE
Improve on "Service not applicable/Does not exist" errors

### ISSUE THREAD

**Issue by jay0lee** [GAM-team/GAM#1720]
Many users run into the "Service not applicable/Does not exist" error. This may be due to lack of DwD set in the admin console or the given Workspace service being disabled for the user. In any case, it's a poor error message that leaves the admin clueless as to how they can rectify the situation (which in turn means lots of group questions for Ross and Jay).

- determine what the actual root issue is, is it DwD, missing scopes? Service disabled?
- determine how GAM may be able to rectify the issue itself, DwD check for the given API scopes before throwing the error? Check licenses of the user before throwing error? Check if service is enabled via new policy API? Any additional info GAM can gather that will provide a better picture of the root issue.
- instruct the admin as to next steps, "DwD authorization incomplete, please run "gam ... check serviceaccount", etc.

@taers232c penny for your thoughts here.

**Comment by taers232c** [comment]
I'm looking at this.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
Fixed in 7.02.00 and 7.02.04
