### ISSUE TITLE
GAM has run out of memory

### ISSUE THREAD

**Issue by amol-d9** [GAM-team/GAM#1723]
Hi Ross,

We are using 64-bit version with good amount of RAM free for GAM to run still we are getting "GAM has run out of memory" error.

Earlier it was running perfectly fine but suddenly it started throwing errors.

Can you suggest what changes required for this?

**Comment by jay0lee** [comment]
What version are you running?

What command are you running? 

How many users are in your domain?

How much RAM does the server have?

**Comment by jay0lee** [comment]
> What version are you running? - GAMADV-XTD3 6.62.05

You need to upgrade to GAM7.

> What command are you running? adv-gam.exe print users allfields 

Don't use all fields unless you actually need every single field. Instead determine which fields you actually care about and only request those. The command will run faster, use less network traffic and less memory.

> How many users are in your domain? - 82K
> How much RAM does the server have? 16GB

I wouldn't consider 16gb a "lot" of memory these days, especially when an os like Windows 11 been consume half of that at boot.

The fact is you may just need to upgrade to more RAM for such a use case. Try the above items first though.

**Comment by jay0lee** [comment]
Closing this. Please reach out on the group if you have further questions.
