### ISSUE TITLE
GAM update on MacOS 15.1.1 not working

### ISSUE THREAD

**Issue by vern3851** [GAM-team/GAM#1727]
im on MacOS 15.1.1 (m3 chip) running GAM 7.00.40

and when i try to upgrade i get:

```
bash <(curl -s -S -L https://git.io/install-gam) -l
Checking GitHub URL https://api.github.com/repos/GAM-team/GAM/releases/latest for latest GAM release (unauthenticated)...

Getting file and download URL...

Sorry, you are running MacOS 15.1 but GAM on arm64 requires MacOS  or newer. Exiting.
```

**Comment by taers232c** [comment]
Short term fix:
go here: https://github.com/GAM-team/GAM/releases/tag/v7.02.00
download: gam-7.02.00-macos15.1-aarch64.tar.xz to ~/bin
do: cd ~/bin
do: tar -xvf gam-7.02.00-macos15.1-aarch64.tar.xz

What do these show:
uname -m
sw_vers -productVersion
echo $(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')

**Comment by vern3851** [comment]
Cheers Ross @taers232c 
manual install worked.

outputs:
uname -m
arm64

sw_vers -productVersion
15.1.1

echo $(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')
15.1

python -V
zsh: command not found: python

python3 -V
Python 3.9.6

**Comment by taers232c** [comment]
Can we do a Meet/Zoom right now?
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
It sounds like GAM is failing to retrieve the release information from GitHub, that's where the required version information is determined. My guess is your device or network is blocking the install script from retrieiving GitHub URLs. What does:

```
curl -vvvv https://api.github.com/repos/GAM-team/GAM/releases/latest
```
show on the machine?

**Comment by vern3851** [comment]
ohh enterprise ssl inspection crap is a very likely cause and im embarresed
to say i didnt try and by-pass that before i reported it here.
i cant easily test that theory on my prod machine as the update bash now
spews an error i dont understand at all:

Checking GitHub URL
https://api.github.com/repos/GAM-team/GAM/releases/latest for latest GAM
release (unauthenticated)...

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File
"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py",
line 293, in load
    return loads(fp.read(),
  File
"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py",
line 346, in loads
    return _default_decoder.decode(s)
  File
"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File
"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
/dev/fd/11: command substitution: line 270: syntax error near unexpected
token `newline'
/dev/fd/11: command substitution: line 270: `  [lL]inux'
/dev/fd/11: line 205: ldd: command not found
This Linux distribution uses glibc
/dev/fd/11: line 245: syntax error near unexpected token `;;'
/dev/fd/11: line 245: `    ;;'

that curl command gives a massive output and im not sure what im
interpreting.

i'll install an older GAM on a test machine with our enterprise ssl
inspection crap on it and try an update with it on and with it by-passed.
if it works fine by-passed then ive done nothing but waste your time :(
Will report back soon.

**Comment by jay0lee** [comment]
That's a temp error I created trying to provide better error reporting
here. Try again in a minute and it should work.

Jay Lee

**Comment by vern3851** [comment]
confirmed, the update command does now work on my production machine (that i manually upped to 7.02.00 earlier.

for me test is the way to get a specific version:
`bash gam-install.sh -v 7.00.38`

**Comment by vern3851** [comment]
on my test machine, with the enterprise ssl inspection stuff:
`bash gam-install.sh -v 7.00.38` did install 7.00.38
then  `bash <(curl -s -S -L https://git.io/install-gam) -l` successfully updated it to 7.02.00
¯\_(ツ)_/¯
