### ISSUE TITLE
gam-install.sh - Linux/MacOS directory builds accumulating old dist-info files

### ISSUE THREAD

**Issue by taers232c** [GAM-team/GAM#1732]
When updating an existing gam7 installation, the tar extraction updates files in the lib subdirectory getting the latest dist-info files but leaves old versions of dest-info files in the directory.
```
mkdir -p "$target_dir"

echo_yellow "Extracting archive to $target_dir"
if [[ "$name" =~ tar.xz|tar.gz|tar ]]; then
  tar $strip_gam -xf "$temp_archive_dir"/"$name" -C "$target_dir"
elif [[ "$name" == *.zip ]]; then
  unzip -o "${temp_archive_dir}/${name}" -d "${target_dir}"
else
  echo "I don't know what to do with files like ${name}. Giving up."
  exit 1
fi
```
Adding this `rm -fr "$target_dir/gam7/lib/*"` after the `mkdir -p "$target_dir"` will empty the lib subdirectory and old dist-info files will not accumulate.

**Comment by jay0lee** [comment]
Does GAM throw an error due to the old files or is it just that we shouldn't leave old files around?

**Comment by taers232c** [comment]
It doesn't throw an error, old file are accumulation.
Clean:
$ du -hs *
352K	GamCommands.txt
840K	GamUpdate.txt
12K	LICENSE
68K	cacerts.pem
8.8M	gam
42M	lib

Old stuff:
$ du -hs *
352K	GamCommands.txt
840K	GamUpdate.txt
12K	LICENSE
68K	cacerts.pem
8.8M	gam
44M	lib

2M of old stuff.

Ross
----
Ross Scroggs
***@***.***

**Comment by jay0lee** [comment]
Yeah so clearing lib just before we extract makes sense. Try adding a -v to
the command so we verbosely report what we're doing just in case there's an
error.
