### ISSUE TITLE
Consider using multistore_file or keyring_storage for OAuth credentials

### ISSUE THREAD

**Issue by jay0lee** [GAM-team/GAM#200]
https://developers.google.com/api-client-library/python/guide/aaa_oauth

We have some options available to us that may simplify credential storage (as well as better protect them). Keyring looks really cool as it uses each platforms native credential storage and provides some level of security against physical hacks. I am concerned though about additional dependencies (especially on Linux) that may make it difficult to use. We may want to provide some optional other storage method if we made keyring the default.

multistore may at least simplify switching credentials without many oauth2.txt\* files.

**Comment by sitecarp** [comment]
Yes, please! I use GAM for multiple instances of Google Apps with various clients. We did a hacky mod of version 3.61 to add a parameter to redirect to the appropriate OAuth file. But those tweaks don't translate to your newer versions, so I'm trapped in the past.

**Comment by mryerse** [comment]
I opened a new issue on this topic, am commenting here too.  Suggest implementing it as an optional configuration, such as an environment variable.  Agree some platforms might not work, but I have used Keyring for similar CLI tools and found that they generally work well on Mac and Windows.  Would be happy to make the contribution.

**Comment by sitecarp** [comment]
Just for the record, we discovered our particular issue could be address by using the OAUTHFILE environment variable introduced in GAM 2.1. My particular needs have already been addressed by existing features and I am no longer modifying GAM core files.

**Comment by jay0lee** [comment]
closing this as GAM7 now supports multiple configss and this is really, really old.
