### ISSUE TITLE
Switch CSV output to use new Sheets API

### ISSUE THREAD

**Issue by jay0lee** [GAM-team/GAM#254]
Investigate using Sheets API v4 for CSV uploads. It offers more flexibility and customization:
- Upload to a specific sheet within a spreadsheet doc.
- Append
- Untested but should not have 400k cell limit of Drive API

https://developers.google.com/sheets/

**Comment by jay0lee** [comment]
@taers232c I believe we now support all of this? Feel free to close this one if we do.

**Comment by taers232c** [comment]
This is supported, cell limit is 10,000,000

Append is not available.
